plugins:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions:
    rubocop-rails: false
    rubocop-rspec_rails: false
  Exclude:
    - db/schema.rb
    - vendor/**/* # needed in CI

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Exclude:
    - spec/benchmarks.rb
