plugins:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions:
    rubocop-rails: false
    rubocop-rspec_rails: false

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false
