services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: better_batch_active_record
      POSTGRES_PASSWORD: better_batch_active_record
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready --username=better_batch_active_record'"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always
