default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: better_batch_active_record
  password: better_batch_active_record
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: better_batch_active_record_test_development

test:
  <<: *default
  database: better_batch_active_record_test_test
